#!/bin/sh

export SHELL=$PLAN9/bin/rc
export TERM=dumb
export mousescrollsize=4
# Get rid of backspace characters in Unix man output.
export PAGER=nobs

exec $PLAN9/bin/acme -a -f $HOME/plan9/fonts/anonpro/anonpro.11.font
