#!/bin/sh

exec /bin/sed "0,/^From: /{s/^From: .*/From: $from/}" |msmtp \
	--host=$host \
	--auth=on \
	--tls=on \
	--tls-certcheck=off \
	--user=$user \
	--passwordeval='9passwd role=client service=imap server=$host user=$user' \
	--from=$user \
	--read-recipients \
	--domain=$(hostname)

